image: Visual Studio 2015

build: false

test_script:
  - ps: |
      # Fail tests execution, if any PS error detected
      $ErrorActionPreference = 'Stop'
      # Download development PowerShell
      Invoke-WebRequest -Headers @{"Authorization"="token $env:GITHUB_TOKEN";"Accept"="application/octet-stream"} -Uri 'https://api.github.com/repos/PowerShell/PowerShell/releases/assets/1536098' -OutFile powershell.zip
      Add-Type -A System.IO.Compression.FileSystem
      [IO.Compression.ZipFile]::ExtractToDirectory("$pwd\powershell.zip", "$pwd\..\powershell")
      # No PowerShell v5, therefore cannot use: Expand-Archive powershell.zip
      # Run tests
      Write-Host -Foreground Green 'Run tests'
      ../powershell/powershell.exe --noprofile -c "`$env:psmodulepath = '$pwd/../powershell/Modules'; Import-Module -Verbose -Force '$PWD/Pester.psd1'; Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.xml"
      # Fail the build if tests failed
      $x = [xml](cat -raw TestsResults.xml)
      if ([int]$x.'test-results'.failures -gt 0)
      {
        throw "$($x.'test-results'.failures) tests failed"
      }

artifacts:
  - path: TestResults.xml
