language: cpp

branches:
  only:
    - master
    - /^test.*$/

git:
  depth: 1000

os:
  - linux
sudo: required
dist: trusty

addons:
  artifacts:
    paths: $(ls powershell*{deb,pkg} | tr "\n" ":")

install:
  - (cd tools && ./download.sh)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm use 2.2.1; fi # Default 2.0.0 Ruby is buggy

script: ./tools/travis.sh
